### PR TITLE
Mention the available dash docset version of the documentation

### PR DESCRIPTION
**Pull request by yanick**

### CODE REVIEW

**Comment by aaronjensen** [comment]
awesome, thanks. If it's ok with you, I'd like to hold off on merging until the docset is available in Dash. Please ping me when that happens. Thanks!

**Comment by yanick** [comment]
Absolutely. I did the docset mostly to scratch my own itch, and shared for giggles. The docset itself has already been submitted to Kapeli (https://github.com/Kapeli/Dash-User-Contributions/pull/1821). I'll make sure to let you know when it get accepted. :-)

**Comment by yanick** [comment]
Ding! We're in the official dash user-contrib feed. :-)

**Comment by aaronjensen** [comment]
That's great, thanks again!

**Pull request merged**
