### PR TITLE
Upgrade to lodash4

### PR DESCRIPTION
**Pull request by aaronjensen**
Before:

```
98127 Jan 14 08:07 updeep-standalone.js
22064 Jan 14 08:07 updeep-standalone.min.js
```

After:

```
134138 Jan 14 08:05 updeep-standalone.js
 29916 Jan 14 08:05 updeep-standalone.min.js
```

### CODE REVIEW

**Comment by aaronjensen** [comment]
@jdalton I'm wanting to upgrade to lodash 4, but it adds 36k (8k minified), is this to be expected? Are there webpack hacks I could be applying to help?

**Comment by aaronjensen** [comment]
webpack stats.json after
[stats.json.txt](https://github.com/substantial/updeep/files/90662/stats.json.txt)

**Comment by jdalton** [comment]
See https://github.com/jdalton/redux/blob/1d8df5984c94f4861d28e4339ce41be6c4ef209b/webpack.config.base.js. 

You can use the `webpack.NormalModuleReplacementPlugin` to remove callback shorthand support by mapping 'lodash/internal/baseIteratee.js' to './toFunction.js'.

**Comment by aaronjensen** [comment]
That certainly helps:

```
91731 Jan 14 08:48 updeep-standalone.js
21118 Jan 14 08:48 updeep-standalone.min.js
```

But given that I expose a wrapped version of reject, it's nice to still support the shorthand syntax. 

tbh, I was hoping that lodash 4 would expose fp functions in such a way that they could be imported in a one off basis instead of having to get the whole she-bang. That would allow me to drop many of the functions in updeep and point to using lodash instead.

**Comment by jdalton** [comment]
> tbh, I was hoping that lodash 4 would expose fp functions in such a way that they could be imported in a one off basis instead of having to get the whole she-bang. 

Good news, that landed by way of https://github.com/lodash/lodash/pull/1779. It'll be in the next release.

**Comment by aaronjensen** [comment]
Awesome. Thanks @epeli and @jdalton!

**Comment by mark-rushakoff** [comment]
@aaronjensen lodash 4.1.0 has been released.  I'm excited for lodash 4 with updeep!

**Comment by aaronjensen** [comment]
@mark-rushakoff I don't think it has yet: https://www.npmjs.com/package/lodash

**Comment by mark-rushakoff** [comment]
My bad. Their readme was updated a couple hours ago for 4.1.0, but you're right, it hasn't been tagged or pushed to npm yet. 

I was so excited for it I couldn't even be bothered to make sure the release was all finished and proper! ;)

**Comment by mark-rushakoff** [comment]
@aaronjensen  When can we expect the next release of updeep that includes lodash 4?

**Comment by aaronjensen** [comment]
@mark-rushakoff 0.13.0 is out, thanks for the reminder. I had looked into deprecating some of the functions first but ran into snags with the way lodash/fp works :disappointed:

**Comment by jdalton** [comment]
Next bump the fp behavior will be configurable :)

**Comment by aaronjensen** [comment]
@jdalton sweet, i'm curious to see how that looks in practice

**Comment by jdalton** [comment]
It'll look like
```js
var convert = require('lodash/fp/convert');

/*
 * @param {Object} [options] The options object.
 * @param {boolean} [options.cap=true] Specify capping iteratee arguments.
 * @param {boolean} [options.curry=true] Specify currying.
 * @param {boolean} [options.fixed=true] Specify fixed arity.
 * @param {boolean} [options.immutable=true] Specify immutable operations.
 * @param {boolean} [options.rearg=true] Specify rearranging arguments.
*/
var remove = convert('remove', _.remove, {
  'cap': false,
  'curry': false,
  'fixed': false,
  'immutable': false,
  'rearg': false
});

**Comment by aaronjensen** [comment]
@jdalton Which argument is it in particular that would enable `reject`'s predicate to take multiple args? is that `cap`? I was afraid it would look like this, but I suppose a webpack loader could help clean it up.

**Comment by jdalton** [comment]
Yep `cap`.

>  I was afraid it would look like this, but I suppose a webpack loader could help clean it up.

Feel free to make suggestions.

**Comment by aaronjensen** [comment]
Well, my suggestion is to make `cap` true by default. I think it is less surprising and lets you use the full power of the lodash functions. 

FWIW I think using `parseInt` w/o a radix is a bad idea any way :smile:

**Pull request merged**
