### PR TITLE
Add dangerously_never_freeze option

### PR DESCRIPTION
**Pull request by gilbox**
process.env.UPDEEP_MODE

### CODE REVIEW

**Comment by gilbox** [comment]
thoughts @aaronjensen ?

**Comment by aaronjensen** [comment]
Sorry @gilbox haven't had a chance to get to this. Thanks for putting this together. I can't say I'm a huge fan of having another flag like this (I was more thinking that we'd have an already built build that would just be not minified, but have freezing disabled. That said, this is likely a rather fringe thing any way so I'll merge this one as is. Thanks!

**Comment by aaronjensen** [comment]
@superRaytin Hey, I saw your fork of updeep: https://github.com/superRaytin/updeep-mutable 

I just wanted to let you know that this is built into updeep now as of this pull request, so feel free to use it if you like. Thanks!

**Comment by aaronjensen** [comment]
Also, @superRaytin, you may want to read through this thread which talks about the caveats of this approach: https://github.com/substantial/updeep/issues/57

Disabling freezing (as you have done in your fork) does not actually make the updates mutatations, it just allows mutation after an update. There's a very important difference there.

**Comment by superRaytin** [comment]
@aaronjensen very glad to hear this, thanks very much!

**Pull request merged**
