### PR TITLE
fix explosion in size function and update readme test/lint commands

### PR DESCRIPTION
**Pull request by ianschuster**
Ran into an issue where the new size function was being passed `null` which led to an error.

Also noticed the readme had outdated info on running the tests/linter.

### CODE REVIEW

**Comment by aaronjensen** [comment]
Thanks! I think that the issue should probably be addressed where `size` is called since `null` doesn't really have a size. @yanick thoughts?

**Comment by yanick** [comment]
Looks good to me!

**Comment by yanick** [comment]
(and :100: for the addition of a test for the issue!)

**Comment by yanick** [comment]
We could also protect ourselves for any non-object case with something like:

```
if( typeof target !== 'object' ) return 0;
if( Array.isArray(target) ) return target.length;
return Object.keys(target).length;
```

or even

```
try { 
  return Array.isArray(target)  ? target.length :  Object.keys(target).length; 
}
catch {
  return 0;
}
```

**Comment by aaronjensen** [comment]
Well, again, I don't know that returning `0` from `size` for `null` is appropriate. `null` is `null`, not an object with no properties or an array with no items.

**Comment by aaronjensen** [comment]
I published 1.2.3 with an alternative fix. Thank you for finding this and the PR!

**Comment by aaronjensen** [comment]
This did bring awareness to the fact that lodash's omit returns `{}` if `null` is provided as the object argument. This is both astonishing and not surprising. It would be a breaking change to make updeep return `null` in this instance. I'd be curious what either of you think about the fact that it returns `{}`?

**Comment by yanick** [comment]
Interesting. But yeah, there is basically 2 paths a library can take:

1. "Whatever weird crap you send me, I'll do my best to uphold my end of the bargain" That's what `omit` does. It has vowed that it'll return an object, and so it does. You provide an integer, or a string as the input? Well, that's messed up, but okay, I'll return an empty object because it's the least insane thing to return.

2. "I am here to protect you from dumb errors. I might hurt you in the process, but it's for your own good". That's the other option, to slap the user and loudly point out that what was passed was not an object, was never an object, and what's wrong with you?

Both approaches have their pros and cons, and as long as expectations are properly set, I think they are fine. 

In our specific case, since updeep is very much linked to lodash, I'd say that echoing their approach is the most sensible thing to do. Even if some specific behaviors makes you twitch a little bit. :-)

**Comment by aaronjensen** [comment]
Yeah, if I still used updeep myself I would probably move to eliminate the lodash dependency and embrace something along the lines of no. 2 above. I’m out of position though so in no place to make a large breaking change with clarity and sureness.

**Comment by yanick** [comment]
> Yeah, if I still used updeep myself I would probably move to eliminate the lodash dependency and embrace something along the lines of no. 2 above. I’m out of position though so in no place to make a large breaking change with clarity and sureness.
> 
 
Legit. And to be honest I don't think it's a burning "OMG this needs to be fixed now!" thing. It's a nice to have for the next big rewrite, but until then, everyone will survive. :-)

**Comment by ianschuster** [comment]
> I published 1.2.3 with an alternative fix. Thank you for finding this and the PR!

@aaronjensen I tried your fix but unfortunately I'm still seeing the error occur, I believe it is because of result being `null` which is then passed into size without a safety check.

Example of code where this issue occurs using updeep:
```
const x = u({
    foo: u.omitBy((a) => { return a === 'bar'; })
  }, {});
  ```

**Comment by aaronjensen** [comment]
I cannot reproduce it with that. Are you able to share a test that fails on master?

**Comment by aaronjensen** [comment]
Actually, it's very likely I messed up the release process. Please try 1.2.4.

**Comment by ianschuster** [comment]
> Actually, it's very likely I messed up the release process. Please try 1.2.4.

You are correct, 1.2.4 appears to have fixed the issue, thank you!

**Comment by aaronjensen** [comment]
You are welcome. Thank you again for the report, and I'm sorry about the mistake with the version.

**Pull request closed without merging**
