### PR TITLE
Documented u.freeze

### PR DESCRIPTION
**Pull request by ansonkao**
Resolves https://github.com/substantial/updeep/issues/52

### CODE REVIEW

**Comment by aaronjensen** [comment]
Great, thanks. Just one style nit, could you add spaces inside the braces please? Thanks!

**Comment by aaronjensen** [comment]
Also may be good to clarify that it returns the original object unchanged in production which is not quite nothing.

**Comment by ansonkao** [comment]
Feedback incorporated!

**Comment by aaronjensen** [comment]
Merged, thanks again.

**Pull request merged**
